# Generated by Django 3.0.7 on 2023-05-23 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('production_date', models.DateField(auto_now_add=True)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.BOM')),
            ],
        ),
        migrations.CreateModel(
            name='BOMRawMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.BOM')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Stock')),
            ],
        ),
        migrations.AddField(
            model_name='bom',
            name='raw_materials',
            field=models.ManyToManyField(through='transactions.BOMRawMaterial', to='inventory.Stock'),
        ),
    ]
