# Generated by Django 3.0.7 on 2023-05-26 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20230525_2122'),
        ('transactions', '0003_auto_20230525_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bomrawmaterial',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='production',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='bomrawmaterial',
            unique_together={('bom', 'raw_material')},
        ),
    ]
