# Generated by Django 3.0.7 on 2023-05-30 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20230526_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='purchase_date',
            field=models.DateField(auto_now=True),
        ),
    ]
